name: Run MiniTest
on:
  push:
    paths:
      - 'lib/**'
      - 'test/**'
      - '.github/workflows/minitest.yml'
jobs:
  run-minitest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run tests
        run: |
          rake test
